'use strict';
// Built-in exercise catalog — searched alongside the user's own exercises so
// logging a set never requires typing an exercise name from scratch.
// category values match the exercises table CHECK constraint:
// push | pull | legs | cardio | core | other

module.exports = [
  // ── PUSH (chest / shoulders / triceps) ──────────────────────────────────
  { name: 'Bench Press',                  category: 'push', keywords: ['flat bench', 'barbell bench'] },
  { name: 'Incline Bench Press',          category: 'push', keywords: ['incline barbell'] },
  { name: 'Decline Bench Press',          category: 'push', keywords: ['decline barbell'] },
  { name: 'Dumbbell Bench Press',         category: 'push', keywords: ['db bench', 'flat dumbbell press'] },
  { name: 'Incline Dumbbell Press',       category: 'push', keywords: ['incline db press'] },
  { name: 'Machine Chest Press',          category: 'push', keywords: ['chest press machine'] },
  { name: 'Push-Up',                      category: 'push', keywords: ['pushup', 'push ups', 'pushups'] },
  { name: 'Diamond Push-Up',              category: 'push', keywords: ['close grip pushup', 'tricep pushup'] },
  { name: 'Dips',                         category: 'push', keywords: ['chest dips', 'tricep dips', 'parallel bar'] },
  { name: 'Cable Fly',                    category: 'push', keywords: ['cable crossover', 'chest fly cable'] },
  { name: 'Dumbbell Fly',                 category: 'push', keywords: ['chest fly', 'flat fly', 'flyes'] },
  { name: 'Pec Deck',                     category: 'push', keywords: ['pec dec', 'butterfly machine'] },
  { name: 'Overhead Press',               category: 'push', keywords: ['ohp', 'military press', 'barbell shoulder press'] },
  { name: 'Dumbbell Shoulder Press',      category: 'push', keywords: ['db shoulder press', 'seated shoulder press'] },
  { name: 'Arnold Press',                 category: 'push', keywords: ['arnold dumbbell press'] },
  { name: 'Machine Shoulder Press',       category: 'push', keywords: ['shoulder press machine'] },
  { name: 'Lateral Raise',                category: 'push', keywords: ['side raise', 'side laterals', 'db lateral'] },
  { name: 'Cable Lateral Raise',          category: 'push', keywords: ['cable side raise'] },
  { name: 'Front Raise',                  category: 'push', keywords: ['db front raise', 'plate raise'] },
  { name: 'Upright Row',                  category: 'push', keywords: ['barbell upright row'] },
  { name: 'Tricep Pushdown',              category: 'push', keywords: ['cable pushdown', 'rope pushdown', 'tricep extension cable'] },
  { name: 'Overhead Tricep Extension',    category: 'push', keywords: ['french press', 'overhead extension', 'tricep overhead'] },
  { name: 'Skull Crusher',                category: 'push', keywords: ['lying tricep extension', 'ez bar skullcrusher'] },
  { name: 'Close-Grip Bench Press',       category: 'push', keywords: ['cgbp', 'close grip bench'] },
  { name: 'Tricep Kickback',              category: 'push', keywords: ['db kickback'] },
  { name: 'Landmine Press',               category: 'push', keywords: ['landmine shoulder press'] },
  { name: 'Pike Push-Up',                 category: 'push', keywords: ['pike pushup', 'shoulder pushup'] },

  // ── PULL (back / biceps / rear delts) ───────────────────────────────────
  { name: 'Pull-Up',                      category: 'pull', keywords: ['pullup', 'pull ups', 'chin over bar'] },
  { name: 'Chin-Up',                      category: 'pull', keywords: ['chinup', 'underhand pullup'] },
  { name: 'Lat Pulldown',                 category: 'pull', keywords: ['pulldown', 'wide grip pulldown', 'lats pulldown'] },
  { name: 'Close-Grip Pulldown',          category: 'pull', keywords: ['v bar pulldown', 'neutral grip pulldown'] },
  { name: 'Barbell Row',                  category: 'pull', keywords: ['bent over row', 'bb row'] },
  { name: 'Dumbbell Row',                 category: 'pull', keywords: ['db row', 'one arm row', 'single arm row'] },
  { name: 'Seated Cable Row',             category: 'pull', keywords: ['cable row', 'low row'] },
  { name: 'T-Bar Row',                    category: 'pull', keywords: ['tbar row', 't bar'] },
  { name: 'Machine Row',                  category: 'pull', keywords: ['hammer strength row', 'row machine'] },
  { name: 'Chest-Supported Row',          category: 'pull', keywords: ['incline db row', 'seal row'] },
  { name: 'Deadlift',                     category: 'pull', keywords: ['conventional deadlift', 'barbell deadlift'] },
  { name: 'Rack Pull',                    category: 'pull', keywords: ['partial deadlift'] },
  { name: 'Face Pull',                    category: 'pull', keywords: ['rope face pull', 'rear delt cable'] },
  { name: 'Reverse Fly',                  category: 'pull', keywords: ['rear delt fly', 'reverse pec deck', 'rear fly'] },
  { name: 'Shrug',                        category: 'pull', keywords: ['barbell shrug', 'db shrug', 'traps'] },
  { name: 'Straight-Arm Pulldown',        category: 'pull', keywords: ['lat prayer', 'rope pullover'] },
  { name: 'Dumbbell Pullover',            category: 'pull', keywords: ['pullover'] },
  { name: 'Barbell Curl',                 category: 'pull', keywords: ['bb curl', 'standing curl'] },
  { name: 'Dumbbell Curl',                category: 'pull', keywords: ['db curl', 'bicep curl', 'alternating curl'] },
  { name: 'Hammer Curl',                  category: 'pull', keywords: ['neutral grip curl'] },
  { name: 'Preacher Curl',                category: 'pull', keywords: ['ez bar preacher', 'scott curl'] },
  { name: 'Incline Dumbbell Curl',        category: 'pull', keywords: ['incline curl'] },
  { name: 'Cable Curl',                   category: 'pull', keywords: ['bayesian curl', 'rope curl'] },
  { name: 'Concentration Curl',           category: 'pull', keywords: ['seated concentration'] },
  { name: 'Spider Curl',                  category: 'pull', keywords: ['prone curl'] },
  { name: 'Reverse Curl',                 category: 'pull', keywords: ['overhand curl', 'forearm curl'] },
  { name: 'Wrist Curl',                   category: 'pull', keywords: ['forearm wrist'] },
  { name: 'Inverted Row',                 category: 'pull', keywords: ['bodyweight row', 'australian pullup'] },

  // ── LEGS (quads / hams / glutes / calves) ───────────────────────────────
  { name: 'Squat',                        category: 'legs', keywords: ['back squat', 'barbell squat'] },
  { name: 'Front Squat',                  category: 'legs', keywords: ['barbell front squat'] },
  { name: 'Goblet Squat',                 category: 'legs', keywords: ['db squat', 'kettlebell squat'] },
  { name: 'Hack Squat',                   category: 'legs', keywords: ['hack squat machine'] },
  { name: 'Smith Machine Squat',          category: 'legs', keywords: ['smith squat'] },
  { name: 'Leg Press',                    category: 'legs', keywords: ['45 degree leg press', 'sled press'] },
  { name: 'Bulgarian Split Squat',        category: 'legs', keywords: ['rear foot elevated', 'split squat bulgarian'] },
  { name: 'Lunge',                        category: 'legs', keywords: ['walking lunge', 'db lunge', 'lunges'] },
  { name: 'Reverse Lunge',                category: 'legs', keywords: ['backward lunge'] },
  { name: 'Step-Up',                      category: 'legs', keywords: ['box step up', 'stepup'] },
  { name: 'Romanian Deadlift',            category: 'legs', keywords: ['rdl', 'stiff leg deadlift'] },
  { name: 'Sumo Deadlift',                category: 'legs', keywords: ['wide stance deadlift'] },
  { name: 'Leg Extension',                category: 'legs', keywords: ['quad extension machine'] },
  { name: 'Leg Curl',                     category: 'legs', keywords: ['hamstring curl', 'lying leg curl', 'seated leg curl'] },
  { name: 'Hip Thrust',                   category: 'legs', keywords: ['barbell hip thrust', 'glute bridge weighted'] },
  { name: 'Glute Bridge',                 category: 'legs', keywords: ['bodyweight bridge'] },
  { name: 'Glute Kickback',               category: 'legs', keywords: ['cable kickback', 'donkey kick'] },
  { name: 'Hip Abduction',                category: 'legs', keywords: ['abductor machine', 'side leg machine'] },
  { name: 'Hip Adduction',                category: 'legs', keywords: ['adductor machine', 'inner thigh'] },
  { name: 'Calf Raise',                   category: 'legs', keywords: ['standing calf raise', 'calves'] },
  { name: 'Seated Calf Raise',            category: 'legs', keywords: ['seated calves'] },
  { name: 'Good Morning',                 category: 'legs', keywords: ['barbell good morning'] },
  { name: 'Wall Sit',                     category: 'legs', keywords: ['wall hold'] },
  { name: 'Pistol Squat',                 category: 'legs', keywords: ['single leg squat'] },
  { name: 'Box Jump',                     category: 'legs', keywords: ['plyo box', 'jump box'] },
  { name: 'Sissy Squat',                  category: 'legs', keywords: ['sissy'] },
  { name: 'Nordic Curl',                  category: 'legs', keywords: ['nordic hamstring'] },

  // ── CARDIO ───────────────────────────────────────────────────────────────
  { name: 'Treadmill Run',                category: 'cardio', keywords: ['treadmill', 'running machine'] },
  { name: 'Treadmill Walk (Incline)',     category: 'cardio', keywords: ['incline walk', '12 3 30', 'walking treadmill'] },
  { name: 'Outdoor Run',                  category: 'cardio', keywords: ['run', 'jog', 'jogging', 'running'] },
  { name: 'Walk',                         category: 'cardio', keywords: ['walking', 'steps', 'evening walk', 'morning walk'] },
  { name: 'Cycling',                      category: 'cardio', keywords: ['bike', 'bicycle', 'stationary bike', 'spin'] },
  { name: 'Rowing Machine',               category: 'cardio', keywords: ['rower', 'erg', 'row cardio'] },
  { name: 'Elliptical',                   category: 'cardio', keywords: ['cross trainer'] },
  { name: 'Stair Climber',                category: 'cardio', keywords: ['stairmaster', 'stairs machine'] },
  { name: 'Jump Rope',                    category: 'cardio', keywords: ['skipping', 'skip rope', 'rope jumps'] },
  { name: 'Swimming',                     category: 'cardio', keywords: ['swim', 'laps', 'pool'] },
  { name: 'HIIT Session',                 category: 'cardio', keywords: ['hiit', 'interval training', 'intervals'] },
  { name: 'Sprints',                      category: 'cardio', keywords: ['sprint intervals', 'track sprints'] },
  { name: 'Burpees',                      category: 'cardio', keywords: ['burpee'] },
  { name: 'Jumping Jacks',                category: 'cardio', keywords: ['star jumps'] },
  { name: 'High Knees',                   category: 'cardio', keywords: ['knee drives'] },
  { name: 'Mountain Climbers',            category: 'cardio', keywords: ['climbers'] },
  { name: 'Battle Ropes',                 category: 'cardio', keywords: ['ropes', 'rope slams'] },
  { name: 'Sled Push',                    category: 'cardio', keywords: ['prowler push'] },
  { name: 'Boxing',                       category: 'cardio', keywords: ['shadow boxing', 'bag work', 'punching bag'] },
  { name: 'Badminton',                    category: 'cardio', keywords: ['shuttlecock'] },
  { name: 'Cricket',                      category: 'cardio', keywords: ['nets', 'cricket practice'] },
  { name: 'Football',                     category: 'cardio', keywords: ['soccer'] },
  { name: 'Basketball',                   category: 'cardio', keywords: ['hoops'] },
  { name: 'Tennis',                       category: 'cardio', keywords: ['lawn tennis'] },
  { name: 'Hiking',                       category: 'cardio', keywords: ['trek', 'trekking', 'hike'] },
  { name: 'Dance / Zumba',                category: 'cardio', keywords: ['zumba', 'dance workout', 'aerobics'] },

  // ── CORE ─────────────────────────────────────────────────────────────────
  { name: 'Plank',                        category: 'core', keywords: ['front plank', 'forearm plank'] },
  { name: 'Side Plank',                   category: 'core', keywords: ['oblique plank'] },
  { name: 'Crunch',                       category: 'core', keywords: ['crunches', 'ab crunch'] },
  { name: 'Bicycle Crunch',               category: 'core', keywords: ['bicycle abs'] },
  { name: 'Sit-Up',                       category: 'core', keywords: ['situp', 'sit ups'] },
  { name: 'Leg Raise',                    category: 'core', keywords: ['lying leg raise', 'leg lifts'] },
  { name: 'Hanging Leg Raise',            category: 'core', keywords: ['hanging knee raise', 'toes to bar'] },
  { name: 'Russian Twist',                category: 'core', keywords: ['twists', 'oblique twist'] },
  { name: 'Ab Wheel Rollout',             category: 'core', keywords: ['ab roller', 'wheel rollout'] },
  { name: 'Cable Crunch',                 category: 'core', keywords: ['kneeling cable crunch', 'rope crunch'] },
  { name: 'Dead Bug',                     category: 'core', keywords: ['deadbug'] },
  { name: 'Bird Dog',                     category: 'core', keywords: ['birddog'] },
  { name: 'Hollow Hold',                  category: 'core', keywords: ['hollow body'] },
  { name: 'V-Up',                         category: 'core', keywords: ['v ups', 'jackknife'] },
  { name: 'Flutter Kicks',                category: 'core', keywords: ['scissor kicks'] },
  { name: 'Woodchopper',                  category: 'core', keywords: ['cable chop', 'wood chop'] },
  { name: 'Superman Hold',                category: 'core', keywords: ['back extension floor', 'superman'] },
  { name: 'Back Extension',               category: 'core', keywords: ['hyperextension', '45 degree back'] },

  // ── OTHER (mobility / recovery / full body) ─────────────────────────────
  { name: 'Yoga Session',                 category: 'other', keywords: ['yoga', 'asanas', 'vinyasa'] },
  { name: 'Surya Namaskar',               category: 'other', keywords: ['sun salutation', 'suryanamaskar'] },
  { name: 'Stretching',                   category: 'other', keywords: ['stretch', 'flexibility', 'cool down'] },
  { name: 'Foam Rolling',                 category: 'other', keywords: ['foam roller', 'myofascial'] },
  { name: 'Kettlebell Swing',             category: 'other', keywords: ['kb swing', 'russian swing'] },
  { name: 'Clean and Press',              category: 'other', keywords: ['power clean', 'clean press'] },
  { name: 'Snatch',                       category: 'other', keywords: ['barbell snatch', 'db snatch'] },
  { name: 'Thruster',                     category: 'other', keywords: ['squat press', 'db thruster'] },
  { name: 'Farmer Carry',                 category: 'other', keywords: ['farmers walk', 'loaded carry'] },
  { name: 'Turkish Get-Up',               category: 'other', keywords: ['tgu', 'getup'] },
  { name: 'Wall Ball',                    category: 'other', keywords: ['med ball throw', 'wallball'] },
  { name: 'Meditation / Breathwork',      category: 'other', keywords: ['pranayama', 'breathing', 'meditation'] },
];
