'use strict';
// Full gym exercise database — browsable like the nutrition food list.
// `category` matches the exercises table CHECK constraint (push|pull|legs|cardio|core|other);
// `muscle` is the finer grouping used for the dropdown browse view.

module.exports = [
  // ════════ CHEST ════════
  { name: 'Barbell Bench Press',             category: 'push', muscle: 'Chest', keywords: ['flat bench', 'bb bench'] },
  { name: 'Incline Barbell Bench Press',     category: 'push', muscle: 'Chest', keywords: ['incline bench'] },
  { name: 'Decline Barbell Bench Press',     category: 'push', muscle: 'Chest', keywords: ['decline bench'] },
  { name: 'Dumbbell Bench Press',            category: 'push', muscle: 'Chest', keywords: ['db bench', 'flat db press'] },
  { name: 'Incline Dumbbell Press',          category: 'push', muscle: 'Chest', keywords: ['incline db'] },
  { name: 'Decline Dumbbell Press',          category: 'push', muscle: 'Chest', keywords: ['decline db'] },
  { name: 'Smith Machine Bench Press',       category: 'push', muscle: 'Chest', keywords: ['smith bench'] },
  { name: 'Smith Machine Incline Press',     category: 'push', muscle: 'Chest', keywords: ['smith incline'] },
  { name: 'Machine Chest Press',             category: 'push', muscle: 'Chest', keywords: ['chest press machine', 'seated chest press'] },
  { name: 'Incline Machine Press',           category: 'push', muscle: 'Chest', keywords: ['incline machine'] },
  { name: 'Floor Press',                     category: 'push', muscle: 'Chest', keywords: ['db floor press'] },
  { name: 'Push-Up',                         category: 'push', muscle: 'Chest', keywords: ['pushup', 'push ups'] },
  { name: 'Wide Push-Up',                    category: 'push', muscle: 'Chest', keywords: ['wide grip pushup'] },
  { name: 'Diamond Push-Up',                 category: 'push', muscle: 'Chest', keywords: ['close grip pushup'] },
  { name: 'Decline Push-Up',                 category: 'push', muscle: 'Chest', keywords: ['feet elevated pushup'] },
  { name: 'Incline Push-Up',                 category: 'push', muscle: 'Chest', keywords: ['hands elevated pushup'] },
  { name: 'Archer Push-Up',                  category: 'push', muscle: 'Chest', keywords: ['archer'] },
  { name: 'Clap Push-Up',                    category: 'push', muscle: 'Chest', keywords: ['plyo pushup', 'explosive pushup'] },
  { name: 'Weighted Push-Up',                category: 'push', muscle: 'Chest', keywords: ['plate pushup'] },
  { name: 'Chest Dips',                      category: 'push', muscle: 'Chest', keywords: ['dips chest lean', 'parallel bar dips'] },
  { name: 'Weighted Dips',                   category: 'push', muscle: 'Chest', keywords: ['belt dips'] },
  { name: 'Dumbbell Fly',                    category: 'push', muscle: 'Chest', keywords: ['flat fly', 'db fly', 'flyes'] },
  { name: 'Incline Dumbbell Fly',            category: 'push', muscle: 'Chest', keywords: ['incline fly'] },
  { name: 'Cable Fly (Mid)',                 category: 'push', muscle: 'Chest', keywords: ['cable crossover', 'mid cable fly'] },
  { name: 'Low-to-High Cable Fly',           category: 'push', muscle: 'Chest', keywords: ['low cable fly', 'upper chest cable'] },
  { name: 'High-to-Low Cable Fly',           category: 'push', muscle: 'Chest', keywords: ['high cable fly', 'lower chest cable'] },
  { name: 'Pec Deck',                        category: 'push', muscle: 'Chest', keywords: ['pec dec', 'butterfly machine', 'machine fly'] },
  { name: 'Svend Press',                     category: 'push', muscle: 'Chest', keywords: ['plate squeeze press'] },
  { name: 'Landmine Chest Press',            category: 'push', muscle: 'Chest', keywords: ['landmine press chest'] },
  { name: 'Dumbbell Pullover (Chest)',       category: 'push', muscle: 'Chest', keywords: ['pullover chest'] },

  // ════════ SHOULDERS ════════
  { name: 'Overhead Press (Barbell)',        category: 'push', muscle: 'Shoulders', keywords: ['ohp', 'military press', 'standing press'] },
  { name: 'Seated Barbell Shoulder Press',   category: 'push', muscle: 'Shoulders', keywords: ['seated ohp'] },
  { name: 'Dumbbell Shoulder Press',         category: 'push', muscle: 'Shoulders', keywords: ['db shoulder press', 'seated db press'] },
  { name: 'Arnold Press',                    category: 'push', muscle: 'Shoulders', keywords: ['arnold'] },
  { name: 'Machine Shoulder Press',          category: 'push', muscle: 'Shoulders', keywords: ['shoulder press machine'] },
  { name: 'Smith Machine Shoulder Press',    category: 'push', muscle: 'Shoulders', keywords: ['smith ohp'] },
  { name: 'Push Press',                      category: 'push', muscle: 'Shoulders', keywords: ['push jerk'] },
  { name: 'Behind-the-Neck Press',           category: 'push', muscle: 'Shoulders', keywords: ['btn press'] },
  { name: 'Z Press',                         category: 'push', muscle: 'Shoulders', keywords: ['seated floor press'] },
  { name: 'Landmine Shoulder Press',         category: 'push', muscle: 'Shoulders', keywords: ['landmine press'] },
  { name: 'Pike Push-Up',                    category: 'push', muscle: 'Shoulders', keywords: ['pike pushup'] },
  { name: 'Handstand Push-Up',               category: 'push', muscle: 'Shoulders', keywords: ['hspu', 'wall handstand'] },
  { name: 'Dumbbell Lateral Raise',          category: 'push', muscle: 'Shoulders', keywords: ['side raise', 'lateral raises', 'side laterals'] },
  { name: 'Cable Lateral Raise',             category: 'push', muscle: 'Shoulders', keywords: ['cable side raise'] },
  { name: 'Machine Lateral Raise',           category: 'push', muscle: 'Shoulders', keywords: ['lateral raise machine'] },
  { name: 'Leaning Lateral Raise',           category: 'push', muscle: 'Shoulders', keywords: ['lean away lateral'] },
  { name: 'Dumbbell Front Raise',            category: 'push', muscle: 'Shoulders', keywords: ['front raises'] },
  { name: 'Plate Front Raise',               category: 'push', muscle: 'Shoulders', keywords: ['plate raise'] },
  { name: 'Cable Front Raise',               category: 'push', muscle: 'Shoulders', keywords: ['front raise cable'] },
  { name: 'Barbell Front Raise',             category: 'push', muscle: 'Shoulders', keywords: ['bb front raise'] },
  { name: 'Rear Delt Fly (Dumbbell)',        category: 'pull', muscle: 'Shoulders', keywords: ['bent over fly', 'rear fly', 'reverse fly db'] },
  { name: 'Reverse Pec Deck',                category: 'pull', muscle: 'Shoulders', keywords: ['rear delt machine', 'reverse fly machine'] },
  { name: 'Cable Rear Delt Fly',             category: 'pull', muscle: 'Shoulders', keywords: ['rear delt cable', 'reverse cable fly'] },
  { name: 'Face Pull',                       category: 'pull', muscle: 'Shoulders', keywords: ['rope face pull'] },
  { name: 'Barbell Upright Row',             category: 'push', muscle: 'Shoulders', keywords: ['upright row'] },
  { name: 'Dumbbell Upright Row',            category: 'push', muscle: 'Shoulders', keywords: ['db upright row'] },
  { name: 'Cable Upright Row',               category: 'push', muscle: 'Shoulders', keywords: ['rope upright row'] },
  { name: 'Barbell Shrug',                   category: 'pull', muscle: 'Shoulders', keywords: ['shrugs', 'traps'] },
  { name: 'Dumbbell Shrug',                  category: 'pull', muscle: 'Shoulders', keywords: ['db shrug'] },
  { name: 'Trap Bar Shrug',                  category: 'pull', muscle: 'Shoulders', keywords: ['hex bar shrug'] },
  { name: 'Behind-the-Back Shrug',           category: 'pull', muscle: 'Shoulders', keywords: ['btb shrug'] },

  // ════════ TRICEPS ════════
  { name: 'Rope Pushdown',                   category: 'push', muscle: 'Triceps', keywords: ['tricep rope', 'rope extension'] },
  { name: 'Straight Bar Pushdown',           category: 'push', muscle: 'Triceps', keywords: ['bar pushdown', 'tricep pushdown'] },
  { name: 'V-Bar Pushdown',                  category: 'push', muscle: 'Triceps', keywords: ['v bar tricep'] },
  { name: 'Reverse-Grip Pushdown',           category: 'push', muscle: 'Triceps', keywords: ['underhand pushdown'] },
  { name: 'Single-Arm Cable Pushdown',       category: 'push', muscle: 'Triceps', keywords: ['one arm pushdown'] },
  { name: 'Overhead Rope Extension',         category: 'push', muscle: 'Triceps', keywords: ['overhead cable tricep', 'french press cable'] },
  { name: 'Overhead Dumbbell Extension',     category: 'push', muscle: 'Triceps', keywords: ['db overhead tricep', 'two hand extension'] },
  { name: 'Single-Arm Overhead Extension',   category: 'push', muscle: 'Triceps', keywords: ['one arm overhead'] },
  { name: 'Skull Crusher (EZ Bar)',          category: 'push', muscle: 'Triceps', keywords: ['skullcrusher', 'lying tricep extension'] },
  { name: 'Dumbbell Skull Crusher',          category: 'push', muscle: 'Triceps', keywords: ['db skullcrusher'] },
  { name: 'Close-Grip Bench Press',          category: 'push', muscle: 'Triceps', keywords: ['cgbp', 'close grip'] },
  { name: 'JM Press',                        category: 'push', muscle: 'Triceps', keywords: ['jm'] },
  { name: 'Bench Dips',                      category: 'push', muscle: 'Triceps', keywords: ['tricep dips bench'] },
  { name: 'Tricep Kickback',                 category: 'push', muscle: 'Triceps', keywords: ['db kickback'] },
  { name: 'Cable Kickback',                  category: 'push', muscle: 'Triceps', keywords: ['kickback cable'] },
  { name: 'Machine Tricep Extension',        category: 'push', muscle: 'Triceps', keywords: ['tricep machine'] },
  { name: 'Diamond Push-Up (Triceps)',       category: 'push', muscle: 'Triceps', keywords: ['tricep pushup'] },

  // ════════ BACK ════════
  { name: 'Deadlift',                        category: 'pull', muscle: 'Back', keywords: ['conventional deadlift', 'barbell deadlift'] },
  { name: 'Sumo Deadlift',                   category: 'pull', muscle: 'Back', keywords: ['sumo'] },
  { name: 'Trap Bar Deadlift',               category: 'pull', muscle: 'Back', keywords: ['hex bar deadlift'] },
  { name: 'Deficit Deadlift',                category: 'pull', muscle: 'Back', keywords: ['deficit'] },
  { name: 'Rack Pull',                       category: 'pull', muscle: 'Back', keywords: ['partial deadlift', 'block pull'] },
  { name: 'Pull-Up',                         category: 'pull', muscle: 'Back', keywords: ['pullup', 'pull ups', 'overhand pullup'] },
  { name: 'Chin-Up',                         category: 'pull', muscle: 'Back', keywords: ['chinup', 'underhand pullup'] },
  { name: 'Neutral-Grip Pull-Up',            category: 'pull', muscle: 'Back', keywords: ['hammer grip pullup'] },
  { name: 'Wide-Grip Pull-Up',               category: 'pull', muscle: 'Back', keywords: ['wide pullup'] },
  { name: 'Weighted Pull-Up',                category: 'pull', muscle: 'Back', keywords: ['belt pullup'] },
  { name: 'Assisted Pull-Up Machine',        category: 'pull', muscle: 'Back', keywords: ['assisted pullup'] },
  { name: 'Negative Pull-Up',                category: 'pull', muscle: 'Back', keywords: ['eccentric pullup'] },
  { name: 'Lat Pulldown (Wide)',             category: 'pull', muscle: 'Back', keywords: ['pulldown', 'wide pulldown', 'lats'] },
  { name: 'Close-Grip Lat Pulldown',         category: 'pull', muscle: 'Back', keywords: ['v bar pulldown', 'neutral pulldown'] },
  { name: 'Reverse-Grip Pulldown',           category: 'pull', muscle: 'Back', keywords: ['underhand pulldown'] },
  { name: 'Single-Arm Pulldown',             category: 'pull', muscle: 'Back', keywords: ['one arm pulldown'] },
  { name: 'Behind-the-Neck Pulldown',        category: 'pull', muscle: 'Back', keywords: ['btn pulldown'] },
  { name: 'Straight-Arm Pulldown',           category: 'pull', muscle: 'Back', keywords: ['lat prayer', 'rope pullover', 'pullover cable'] },
  { name: 'Barbell Row',                     category: 'pull', muscle: 'Back', keywords: ['bent over row', 'bb row'] },
  { name: 'Pendlay Row',                     category: 'pull', muscle: 'Back', keywords: ['pendlay'] },
  { name: 'Underhand Barbell Row',           category: 'pull', muscle: 'Back', keywords: ['yates row', 'reverse grip row'] },
  { name: 'Dumbbell Row',                    category: 'pull', muscle: 'Back', keywords: ['db row', 'one arm row', 'single arm row'] },
  { name: 'Kroc Row',                        category: 'pull', muscle: 'Back', keywords: ['heavy db row'] },
  { name: 'Chest-Supported Row',             category: 'pull', muscle: 'Back', keywords: ['incline db row', 'seal row'] },
  { name: 'T-Bar Row',                       category: 'pull', muscle: 'Back', keywords: ['tbar', 't bar'] },
  { name: 'Landmine Row',                    category: 'pull', muscle: 'Back', keywords: ['meadows row'] },
  { name: 'Seated Cable Row (Close)',        category: 'pull', muscle: 'Back', keywords: ['cable row', 'low row', 'v bar row'] },
  { name: 'Seated Cable Row (Wide)',         category: 'pull', muscle: 'Back', keywords: ['wide cable row'] },
  { name: 'Single-Arm Cable Row',            category: 'pull', muscle: 'Back', keywords: ['one arm cable row'] },
  { name: 'Machine Row (High)',              category: 'pull', muscle: 'Back', keywords: ['high row machine'] },
  { name: 'Machine Row (Low)',               category: 'pull', muscle: 'Back', keywords: ['low row machine', 'hammer strength row'] },
  { name: 'Inverted Row',                    category: 'pull', muscle: 'Back', keywords: ['bodyweight row', 'australian pullup'] },
  { name: 'Dumbbell Pullover',               category: 'pull', muscle: 'Back', keywords: ['pullover'] },
  { name: 'Machine Pullover',                category: 'pull', muscle: 'Back', keywords: ['pullover machine'] },
  { name: 'Back Extension',                  category: 'pull', muscle: 'Back', keywords: ['hyperextension', '45 degree back'] },
  { name: 'Good Morning',                    category: 'pull', muscle: 'Back', keywords: ['barbell good morning'] },
  { name: 'Superman Hold',                   category: 'pull', muscle: 'Back', keywords: ['superman'] },

  // ════════ BICEPS & FOREARMS ════════
  { name: 'Barbell Curl',                    category: 'pull', muscle: 'Biceps', keywords: ['bb curl', 'standing barbell curl'] },
  { name: 'EZ Bar Curl',                     category: 'pull', muscle: 'Biceps', keywords: ['ez curl'] },
  { name: 'Dumbbell Curl',                   category: 'pull', muscle: 'Biceps', keywords: ['db curl', 'bicep curl'] },
  { name: 'Alternating Dumbbell Curl',       category: 'pull', muscle: 'Biceps', keywords: ['alternate curl'] },
  { name: 'Hammer Curl',                     category: 'pull', muscle: 'Biceps', keywords: ['neutral curl'] },
  { name: 'Cross-Body Hammer Curl',          category: 'pull', muscle: 'Biceps', keywords: ['pinwheel curl'] },
  { name: 'Rope Hammer Curl',                category: 'pull', muscle: 'Biceps', keywords: ['cable hammer'] },
  { name: 'Preacher Curl (EZ Bar)',          category: 'pull', muscle: 'Biceps', keywords: ['preacher', 'scott curl'] },
  { name: 'Dumbbell Preacher Curl',          category: 'pull', muscle: 'Biceps', keywords: ['db preacher'] },
  { name: 'Machine Preacher Curl',           category: 'pull', muscle: 'Biceps', keywords: ['curl machine', 'machine bicep'] },
  { name: 'Incline Dumbbell Curl',           category: 'pull', muscle: 'Biceps', keywords: ['incline curl'] },
  { name: 'Concentration Curl',              category: 'pull', muscle: 'Biceps', keywords: ['concentration'] },
  { name: 'Spider Curl',                     category: 'pull', muscle: 'Biceps', keywords: ['prone curl'] },
  { name: 'Cable Curl (Bar)',                category: 'pull', muscle: 'Biceps', keywords: ['cable bicep curl'] },
  { name: 'Bayesian Cable Curl',             category: 'pull', muscle: 'Biceps', keywords: ['behind body cable curl'] },
  { name: 'High Cable Curl',                 category: 'pull', muscle: 'Biceps', keywords: ['crucifix curl'] },
  { name: 'Drag Curl',                       category: 'pull', muscle: 'Biceps', keywords: ['drag'] },
  { name: 'Zottman Curl',                    category: 'pull', muscle: 'Biceps', keywords: ['zottman'] },
  { name: '21s (Bicep Curl)',                category: 'pull', muscle: 'Biceps', keywords: ['twenty ones', 'curl 21'] },
  { name: 'Reverse Curl',                    category: 'pull', muscle: 'Forearms', keywords: ['overhand curl'] },
  { name: 'Wrist Curl',                      category: 'pull', muscle: 'Forearms', keywords: ['forearm curl'] },
  { name: 'Reverse Wrist Curl',              category: 'pull', muscle: 'Forearms', keywords: ['wrist extension'] },
  { name: 'Behind-the-Back Wrist Curl',      category: 'pull', muscle: 'Forearms', keywords: ['btb wrist curl'] },
  { name: 'Farmer Hold',                     category: 'pull', muscle: 'Forearms', keywords: ['grip hold', 'static hold'] },
  { name: 'Plate Pinch',                     category: 'pull', muscle: 'Forearms', keywords: ['pinch grip'] },
  { name: 'Wrist Roller',                    category: 'pull', muscle: 'Forearms', keywords: ['roller forearm'] },
  { name: 'Dead Hang',                       category: 'pull', muscle: 'Forearms', keywords: ['bar hang'] },

  // ════════ QUADS ════════
  { name: 'Back Squat',                      category: 'legs', muscle: 'Quads', keywords: ['squat', 'barbell squat'] },
  { name: 'Front Squat',                     category: 'legs', muscle: 'Quads', keywords: ['front rack squat'] },
  { name: 'Box Squat',                       category: 'legs', muscle: 'Quads', keywords: ['squat to box'] },
  { name: 'Pause Squat',                     category: 'legs', muscle: 'Quads', keywords: ['paused squat'] },
  { name: 'Goblet Squat',                    category: 'legs', muscle: 'Quads', keywords: ['db squat', 'kettlebell squat'] },
  { name: 'Zercher Squat',                   category: 'legs', muscle: 'Quads', keywords: ['zercher'] },
  { name: 'Overhead Squat',                  category: 'legs', muscle: 'Quads', keywords: ['ohs'] },
  { name: 'Smith Machine Squat',             category: 'legs', muscle: 'Quads', keywords: ['smith squat'] },
  { name: 'Hack Squat (Machine)',            category: 'legs', muscle: 'Quads', keywords: ['hack squat'] },
  { name: 'Pendulum Squat',                  category: 'legs', muscle: 'Quads', keywords: ['pendulum'] },
  { name: 'Belt Squat',                      category: 'legs', muscle: 'Quads', keywords: ['hip belt squat'] },
  { name: 'Leg Press (45°)',                 category: 'legs', muscle: 'Quads', keywords: ['leg press', 'sled press'] },
  { name: 'Horizontal Leg Press',            category: 'legs', muscle: 'Quads', keywords: ['seated leg press'] },
  { name: 'Single-Leg Press',                category: 'legs', muscle: 'Quads', keywords: ['one leg press'] },
  { name: 'Leg Extension',                   category: 'legs', muscle: 'Quads', keywords: ['quad extension'] },
  { name: 'Single-Leg Extension',            category: 'legs', muscle: 'Quads', keywords: ['one leg extension'] },
  { name: 'Walking Lunge',                   category: 'legs', muscle: 'Quads', keywords: ['lunges', 'db lunge'] },
  { name: 'Reverse Lunge',                   category: 'legs', muscle: 'Quads', keywords: ['backward lunge'] },
  { name: 'Lateral Lunge',                   category: 'legs', muscle: 'Quads', keywords: ['side lunge'] },
  { name: 'Curtsy Lunge',                    category: 'legs', muscle: 'Quads', keywords: ['curtsy'] },
  { name: 'Smith Machine Lunge',             category: 'legs', muscle: 'Quads', keywords: ['smith lunge'] },
  { name: 'Bulgarian Split Squat',           category: 'legs', muscle: 'Quads', keywords: ['rear foot elevated', 'bss'] },
  { name: 'Split Squat',                     category: 'legs', muscle: 'Quads', keywords: ['static lunge'] },
  { name: 'Step-Up',                         category: 'legs', muscle: 'Quads', keywords: ['box step up'] },
  { name: 'Sissy Squat',                     category: 'legs', muscle: 'Quads', keywords: ['sissy'] },
  { name: 'Pistol Squat',                    category: 'legs', muscle: 'Quads', keywords: ['single leg squat'] },
  { name: 'Wall Sit',                        category: 'legs', muscle: 'Quads', keywords: ['wall hold'] },
  { name: 'Jump Squat',                      category: 'legs', muscle: 'Quads', keywords: ['squat jumps'] },
  { name: 'Box Jump',                        category: 'legs', muscle: 'Quads', keywords: ['plyo box'] },

  // ════════ HAMSTRINGS & GLUTES ════════
  { name: 'Romanian Deadlift',               category: 'legs', muscle: 'Hamstrings', keywords: ['rdl'] },
  { name: 'Dumbbell Romanian Deadlift',      category: 'legs', muscle: 'Hamstrings', keywords: ['db rdl'] },
  { name: 'Single-Leg RDL',                  category: 'legs', muscle: 'Hamstrings', keywords: ['single leg deadlift'] },
  { name: 'Stiff-Leg Deadlift',              category: 'legs', muscle: 'Hamstrings', keywords: ['sldl', 'straight leg deadlift'] },
  { name: 'Lying Leg Curl',                  category: 'legs', muscle: 'Hamstrings', keywords: ['leg curl', 'hamstring curl'] },
  { name: 'Seated Leg Curl',                 category: 'legs', muscle: 'Hamstrings', keywords: ['seated hamstring'] },
  { name: 'Standing Single-Leg Curl',        category: 'legs', muscle: 'Hamstrings', keywords: ['standing leg curl'] },
  { name: 'Nordic Curl',                     category: 'legs', muscle: 'Hamstrings', keywords: ['nordic hamstring'] },
  { name: 'Swiss Ball Leg Curl',             category: 'legs', muscle: 'Hamstrings', keywords: ['stability ball curl'] },
  { name: 'Glute Ham Raise',                 category: 'legs', muscle: 'Hamstrings', keywords: ['ghr', 'ghd raise'] },
  { name: 'Barbell Hip Thrust',              category: 'legs', muscle: 'Glutes', keywords: ['hip thrust'] },
  { name: 'Machine Hip Thrust',              category: 'legs', muscle: 'Glutes', keywords: ['thrust machine'] },
  { name: 'Single-Leg Hip Thrust',           category: 'legs', muscle: 'Glutes', keywords: ['one leg thrust'] },
  { name: 'Glute Bridge',                    category: 'legs', muscle: 'Glutes', keywords: ['bridge'] },
  { name: 'Cable Glute Kickback',            category: 'legs', muscle: 'Glutes', keywords: ['kickback glute', 'donkey kick cable'] },
  { name: 'Machine Glute Kickback',          category: 'legs', muscle: 'Glutes', keywords: ['kickback machine'] },
  { name: 'Hip Abduction Machine',           category: 'legs', muscle: 'Glutes', keywords: ['abductor', 'outer thigh'] },
  { name: 'Hip Adduction Machine',           category: 'legs', muscle: 'Glutes', keywords: ['adductor', 'inner thigh'] },
  { name: 'Cable Hip Abduction',             category: 'legs', muscle: 'Glutes', keywords: ['cable abduction'] },
  { name: 'Banded Lateral Walk',             category: 'legs', muscle: 'Glutes', keywords: ['monster walk', 'band walk'] },
  { name: 'Frog Pump',                       category: 'legs', muscle: 'Glutes', keywords: ['frog bridge'] },
  { name: 'Sumo Squat',                      category: 'legs', muscle: 'Glutes', keywords: ['wide squat', 'plie squat'] },

  // ════════ CALVES ════════
  { name: 'Standing Calf Raise (Machine)',   category: 'legs', muscle: 'Calves', keywords: ['calf raise', 'calves'] },
  { name: 'Seated Calf Raise',               category: 'legs', muscle: 'Calves', keywords: ['seated calves'] },
  { name: 'Calf Raise on Leg Press',         category: 'legs', muscle: 'Calves', keywords: ['leg press calves'] },
  { name: 'Smith Machine Calf Raise',        category: 'legs', muscle: 'Calves', keywords: ['smith calves'] },
  { name: 'Single-Leg Calf Raise',           category: 'legs', muscle: 'Calves', keywords: ['one leg calf'] },
  { name: 'Donkey Calf Raise',               category: 'legs', muscle: 'Calves', keywords: ['donkey calves'] },
  { name: 'Tibialis Raise',                  category: 'legs', muscle: 'Calves', keywords: ['tib raise', 'shin raise'] },

  // ════════ CORE ════════
  { name: 'Plank',                           category: 'core', muscle: 'Core', keywords: ['forearm plank'] },
  { name: 'Weighted Plank',                  category: 'core', muscle: 'Core', keywords: ['plate plank'] },
  { name: 'Side Plank',                      category: 'core', muscle: 'Core', keywords: ['oblique plank'] },
  { name: 'RKC Plank',                       category: 'core', muscle: 'Core', keywords: ['hard plank'] },
  { name: 'Crunch',                          category: 'core', muscle: 'Core', keywords: ['crunches'] },
  { name: 'Bicycle Crunch',                  category: 'core', muscle: 'Core', keywords: ['bicycle abs'] },
  { name: 'Reverse Crunch',                  category: 'core', muscle: 'Core', keywords: ['reverse abs'] },
  { name: 'Decline Crunch',                  category: 'core', muscle: 'Core', keywords: ['decline abs'] },
  { name: 'Cable Crunch',                    category: 'core', muscle: 'Core', keywords: ['kneeling crunch', 'rope crunch'] },
  { name: 'Machine Crunch',                  category: 'core', muscle: 'Core', keywords: ['ab machine'] },
  { name: 'Sit-Up',                          category: 'core', muscle: 'Core', keywords: ['situp', 'sit ups'] },
  { name: 'Weighted Sit-Up',                 category: 'core', muscle: 'Core', keywords: ['plate situp'] },
  { name: 'GHD Sit-Up',                      category: 'core', muscle: 'Core', keywords: ['ghd abs'] },
  { name: 'Lying Leg Raise',                 category: 'core', muscle: 'Core', keywords: ['leg raises', 'leg lifts'] },
  { name: 'Hanging Knee Raise',              category: 'core', muscle: 'Core', keywords: ['knee raise'] },
  { name: 'Hanging Leg Raise',               category: 'core', muscle: 'Core', keywords: ['hanging raise'] },
  { name: 'Toes to Bar',                     category: 'core', muscle: 'Core', keywords: ['t2b'] },
  { name: "Captain's Chair Leg Raise",       category: 'core', muscle: 'Core', keywords: ['vertical knee raise', 'roman chair'] },
  { name: 'Russian Twist',                   category: 'core', muscle: 'Core', keywords: ['twists'] },
  { name: 'Ab Wheel Rollout',                category: 'core', muscle: 'Core', keywords: ['ab roller'] },
  { name: 'Dead Bug',                        category: 'core', muscle: 'Core', keywords: ['deadbug'] },
  { name: 'Bird Dog',                        category: 'core', muscle: 'Core', keywords: ['birddog'] },
  { name: 'Hollow Hold',                     category: 'core', muscle: 'Core', keywords: ['hollow body'] },
  { name: 'V-Up',                            category: 'core', muscle: 'Core', keywords: ['jackknife'] },
  { name: 'Flutter Kicks',                   category: 'core', muscle: 'Core', keywords: ['flutters'] },
  { name: 'Scissor Kicks',                   category: 'core', muscle: 'Core', keywords: ['scissors abs'] },
  { name: 'Mountain Climbers',               category: 'core', muscle: 'Core', keywords: ['climbers'] },
  { name: 'Cable Woodchopper (High-to-Low)', category: 'core', muscle: 'Core', keywords: ['woodchop', 'cable chop'] },
  { name: 'Cable Woodchopper (Low-to-High)', category: 'core', muscle: 'Core', keywords: ['reverse chop'] },
  { name: 'Pallof Press',                    category: 'core', muscle: 'Core', keywords: ['anti rotation press'] },
  { name: 'Landmine Rotation',               category: 'core', muscle: 'Core', keywords: ['landmine twist'] },
  { name: 'Dumbbell Side Bend',              category: 'core', muscle: 'Core', keywords: ['side bends'] },
  { name: 'Dragon Flag',                     category: 'core', muscle: 'Core', keywords: ['dragonflag'] },
  { name: 'L-Sit',                           category: 'core', muscle: 'Core', keywords: ['lsit'] },
  { name: 'Bear Crawl',                      category: 'core', muscle: 'Core', keywords: ['crawl'] },

  // ════════ CARDIO ════════
  { name: 'Treadmill Run',                   category: 'cardio', muscle: 'Cardio', keywords: ['treadmill'] },
  { name: 'Treadmill Walk (Incline)',        category: 'cardio', muscle: 'Cardio', keywords: ['incline walk', '12 3 30'] },
  { name: 'Treadmill Sprint Intervals',      category: 'cardio', muscle: 'Cardio', keywords: ['treadmill sprints'] },
  { name: 'Outdoor Run',                     category: 'cardio', muscle: 'Cardio', keywords: ['run', 'jog', 'jogging', 'running'] },
  { name: 'Walk',                            category: 'cardio', muscle: 'Cardio', keywords: ['walking', 'steps'] },
  { name: 'Sprints (Track)',                 category: 'cardio', muscle: 'Cardio', keywords: ['sprint'] },
  { name: 'Stationary Bike',                 category: 'cardio', muscle: 'Cardio', keywords: ['bike', 'cycling machine', 'spin bike'] },
  { name: 'Assault Bike',                    category: 'cardio', muscle: 'Cardio', keywords: ['air bike', 'airdyne'] },
  { name: 'Recumbent Bike',                  category: 'cardio', muscle: 'Cardio', keywords: ['recumbent'] },
  { name: 'Outdoor Cycling',                 category: 'cardio', muscle: 'Cardio', keywords: ['cycle', 'bicycle ride'] },
  { name: 'Rowing Machine',                  category: 'cardio', muscle: 'Cardio', keywords: ['rower', 'erg'] },
  { name: 'Ski Erg',                         category: 'cardio', muscle: 'Cardio', keywords: ['skierg'] },
  { name: 'Elliptical',                      category: 'cardio', muscle: 'Cardio', keywords: ['cross trainer'] },
  { name: 'Stair Climber',                   category: 'cardio', muscle: 'Cardio', keywords: ['stairmaster', 'stepmill'] },
  { name: "Jacob's Ladder",                  category: 'cardio', muscle: 'Cardio', keywords: ['jacobs ladder'] },
  { name: 'Jump Rope',                       category: 'cardio', muscle: 'Cardio', keywords: ['skipping', 'skip rope'] },
  { name: 'Double Unders',                   category: 'cardio', muscle: 'Cardio', keywords: ['double under'] },
  { name: 'Swimming',                        category: 'cardio', muscle: 'Cardio', keywords: ['swim', 'laps'] },
  { name: 'HIIT Session',                    category: 'cardio', muscle: 'Cardio', keywords: ['hiit', 'intervals'] },
  { name: 'Burpees',                         category: 'cardio', muscle: 'Cardio', keywords: ['burpee'] },
  { name: 'Jumping Jacks',                   category: 'cardio', muscle: 'Cardio', keywords: ['star jumps'] },
  { name: 'High Knees',                      category: 'cardio', muscle: 'Cardio', keywords: ['knee drives'] },
  { name: 'Butt Kicks',                      category: 'cardio', muscle: 'Cardio', keywords: ['heel kicks'] },
  { name: 'Battle Ropes',                    category: 'cardio', muscle: 'Cardio', keywords: ['ropes', 'rope slams'] },
  { name: 'Sled Push',                       category: 'cardio', muscle: 'Cardio', keywords: ['prowler'] },
  { name: 'Sled Pull',                       category: 'cardio', muscle: 'Cardio', keywords: ['sled drag'] },
  { name: 'Boxing (Bag Work)',               category: 'cardio', muscle: 'Cardio', keywords: ['punching bag', 'heavy bag'] },
  { name: 'Shadow Boxing',                   category: 'cardio', muscle: 'Cardio', keywords: ['shadowboxing'] },
  { name: 'Kickboxing',                      category: 'cardio', muscle: 'Cardio', keywords: ['kick boxing'] },
  { name: 'Badminton',                       category: 'cardio', muscle: 'Sports', keywords: ['shuttle'] },
  { name: 'Cricket',                         category: 'cardio', muscle: 'Sports', keywords: ['nets'] },
  { name: 'Football',                        category: 'cardio', muscle: 'Sports', keywords: ['soccer'] },
  { name: 'Basketball',                      category: 'cardio', muscle: 'Sports', keywords: ['hoops'] },
  { name: 'Tennis',                          category: 'cardio', muscle: 'Sports', keywords: ['lawn tennis'] },
  { name: 'Table Tennis',                    category: 'cardio', muscle: 'Sports', keywords: ['ping pong', 'tt'] },
  { name: 'Squash',                          category: 'cardio', muscle: 'Sports', keywords: ['squash court'] },
  { name: 'Volleyball',                      category: 'cardio', muscle: 'Sports', keywords: ['volley'] },
  { name: 'Hiking',                          category: 'cardio', muscle: 'Sports', keywords: ['trek', 'trekking'] },
  { name: 'Skating',                         category: 'cardio', muscle: 'Sports', keywords: ['skate', 'rollerblade'] },
  { name: 'Dance / Zumba',                   category: 'cardio', muscle: 'Sports', keywords: ['zumba', 'aerobics'] },

  // ════════ FULL BODY / FUNCTIONAL ════════
  { name: 'Kettlebell Swing',                category: 'other', muscle: 'Full Body', keywords: ['kb swing'] },
  { name: 'Kettlebell Clean',                category: 'other', muscle: 'Full Body', keywords: ['kb clean'] },
  { name: 'Kettlebell Snatch',               category: 'other', muscle: 'Full Body', keywords: ['kb snatch'] },
  { name: 'Kettlebell Press',                category: 'other', muscle: 'Full Body', keywords: ['kb press'] },
  { name: 'Kettlebell Windmill',             category: 'other', muscle: 'Full Body', keywords: ['windmill'] },
  { name: 'Turkish Get-Up',                  category: 'other', muscle: 'Full Body', keywords: ['tgu', 'getup'] },
  { name: 'Power Clean',                     category: 'other', muscle: 'Full Body', keywords: ['clean'] },
  { name: 'Hang Clean',                      category: 'other', muscle: 'Full Body', keywords: ['hang power clean'] },
  { name: 'Clean and Jerk',                  category: 'other', muscle: 'Full Body', keywords: ['c and j'] },
  { name: 'Clean and Press',                 category: 'other', muscle: 'Full Body', keywords: ['clean press'] },
  { name: 'Barbell Snatch',                  category: 'other', muscle: 'Full Body', keywords: ['snatch'] },
  { name: 'Dumbbell Snatch',                 category: 'other', muscle: 'Full Body', keywords: ['db snatch'] },
  { name: 'Thruster',                        category: 'other', muscle: 'Full Body', keywords: ['squat press'] },
  { name: 'Man Maker',                       category: 'other', muscle: 'Full Body', keywords: ['manmaker'] },
  { name: 'Devil Press',                     category: 'other', muscle: 'Full Body', keywords: ['devils press'] },
  { name: 'Farmer Carry',                    category: 'other', muscle: 'Full Body', keywords: ['farmers walk', 'loaded carry'] },
  { name: 'Suitcase Carry',                  category: 'other', muscle: 'Full Body', keywords: ['single side carry'] },
  { name: 'Overhead Carry',                  category: 'other', muscle: 'Full Body', keywords: ['waiter walk'] },
  { name: 'Wall Ball',                       category: 'other', muscle: 'Full Body', keywords: ['wallball', 'med ball throw'] },
  { name: 'Medicine Ball Slam',              category: 'other', muscle: 'Full Body', keywords: ['ball slam'] },
  { name: 'Tire Flip',                       category: 'other', muscle: 'Full Body', keywords: ['tyre flip'] },
  { name: 'Broad Jump',                      category: 'other', muscle: 'Full Body', keywords: ['standing long jump'] },

  // ════════ MOBILITY & RECOVERY ════════
  { name: 'Yoga Session',                    category: 'other', muscle: 'Mobility', keywords: ['yoga', 'asanas', 'vinyasa'] },
  { name: 'Surya Namaskar',                  category: 'other', muscle: 'Mobility', keywords: ['sun salutation'] },
  { name: 'Pilates',                         category: 'other', muscle: 'Mobility', keywords: ['mat pilates'] },
  { name: 'Stretching',                      category: 'other', muscle: 'Mobility', keywords: ['stretch', 'cool down'] },
  { name: 'Dynamic Warm-Up',                 category: 'other', muscle: 'Mobility', keywords: ['warmup', 'warm up'] },
  { name: 'Foam Rolling',                    category: 'other', muscle: 'Mobility', keywords: ['foam roller'] },
  { name: 'Hip Mobility Drills',             category: 'other', muscle: 'Mobility', keywords: ['90 90', 'hip openers'] },
  { name: 'Shoulder Mobility (Band)',        category: 'other', muscle: 'Mobility', keywords: ['band dislocates', 'shoulder pass through'] },
  { name: "World's Greatest Stretch",        category: 'other', muscle: 'Mobility', keywords: ['lunge stretch'] },
  { name: 'Cat-Cow Stretch',                 category: 'other', muscle: 'Mobility', keywords: ['cat camel'] },
  { name: 'Meditation / Breathwork',         category: 'other', muscle: 'Mobility', keywords: ['pranayama', 'breathing'] },
];
